---
- name: Configure MacOS device.
  hosts: localhost
  connection: local

  vars_files:
    - vars/macbook.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
#    - role: geerlingguy.dotfiles
#      when: configure_dotfiles
#      tags: ['dotfiles']
#    - role: geerlingguy.mac.mas
#      when: mas_installed_apps or mas_installed_app_ids
#      tags: ['mas']
    - role: geerlingguy.mac.dock
      tags: ['dock']

  tasks:
    # Setup Hostname
    - block:
      - name: Rename device (network name)
        command: scutil --set HostName {{ desired_name }}
        become: yes
      - name: Rename computer name
        command: scutil --set ComputerName {{ desired_name }}
        become: yes

    # Setup Accounts
    - block:
      - name: Open Account Settings
        command: open /System/Library/PreferencePanes/InternetAccounts.prefPane
        become: no
      - name: Notification to manually add Accounts
        command: osascript -e 'display dialog "Please add your Account manually by navigating to System Preferences > Internet Accounts. \nClick Ok once done." with title "Manual Action Required" buttons {"Ok"}'
        become: no
