---
- name: Setup ssh port
  hosts: vps
  gather_facts: false

  tasks:
    - name: SSH Port Juggle
      ansible.builtin.import_tasks: tasks/sshd_port_juggling.yml
      when: testing is undefined or testing != 'true'
    - name: SSH User Juggle
      ansible.builtin.import_tasks: tasks/sshd_login_user_juggling.yml
      when: testing is undefined or testing != 'true'
    - name: For testing at github actions set username to "runneradmin"
      ansible.builtin.set_fact:
        username: "runneradmin"
      when: testing is defined and testing == 'true'
    - name: Stop pre-built DNS server
      ansible.builtin.command: systemctl stop systemd-resolved
      become: true
      changed_when: false
      when: testing is defined and testing == 'true'


- name: Configure VPS personal server.
  hosts: vps

  vars_files:
    - vars/all.yml
    - vars/vps.yml


  roles:
    - role: packages_install
      become: true

    - role: linux_server_setup
      vars:
        linux_server_setup_hostname: "{{ device_name }}"
        linux_server_setup_login_user: "{{ username }}"
        linux_server_setup_login_password: "{{ password }}"
        linux_server_setup_login_user_uid: 1000
        linux_server_setup_login_user_gid: 1000
        linux_server_setup_login_ssh_public_key: "{{ lookup('file', '{{ ssh_public_key_path }}') }}"
        linux_server_setup_open_ports:
          - {port: 22, protocol: "tcp", comment: "default ssh"}
          - {port: "{{ ssh_port }}", protocol: "tcp", comment: "custom ssh"}
          - {port: 51820, protocol: "udp", comment: "wireguard"}
          - {port: 80, protocol: "tcp", comment: "http"}
          - {port: 443, protocol: "tcp", comment: "https"}

    - role: hifis.unattended_upgrades
      vars:
        unattended_automatic_reboot_time: 04:00  # noqa: var-naming[no-role-prefix]
        # apt-daily timer
        unattended_apt_daily_oncalendar: "*-*-* 01:00"  # noqa: var-naming[no-role-prefix]
        unattended_apt_daily_randomizeddelaysec: "60m"  # noqa: var-naming[no-role-prefix]
        # apt-daily-upgrade timer
        unattended_apt_daily_upgrade_oncalendar: "*-*-* 2:00"  # noqa: var-naming[no-role-prefix]
        unattended_apt_daily_upgrade_randomizeddelaysec: "60m"  # noqa: var-naming[no-role-prefix]
      become: true

    - role: geerlingguy.security
      security_ssh_port: "{{ ssh_port }}"
      security_ssh_permit_root_login: "no"
      become: true

    - role: geerlingguy.docker
      become: true

    - role: zsh_setup
      vars:
        zsh_setup_set_default_shell: true
        zsh_setup_config_src: files/.zshrc.style-config-block.zsh
        zsh_setup_user: "{{ username }}"
      become: true


  tasks:
    - name: Copy docker configs and run containers
      ansible.builtin.include_role:
        name: containers_setup
      vars:
        containers_setup_user: "{{ username }}"
        containers_setup_configs_dir: "{{ services_configs_dir }}"
        containers_setup_data_dir: "{{ services_data_dir }}"
        containers_setup_docker_compose_template: "files/vps/docker-compose.yml.j2"
        containers_setup_make_dirs: []
#          - "{{ services_data_dir }}/influxdb-data"
#          - "{{ services_configs_dir }}/influxdb-config"
        containers_setup_touch_files: []
        containers_setup_config_templates:
          files/vps/server-wg0.conf.j2: "server-wg0.conf"
#          files/vps/telegraf.conf: "{{ services_configs_dir }}/telegraf.conf"
