---

- name: Install remote management libs and make docker folders
  ansible.builtin.import_tasks: install.yml
  tags: [docker]

- name: Copy templates
  ansible.builtin.import_tasks: templates.yml
  tags: [docker]

- name: Run docker compose
  ansible.builtin.command:
    cmd: docker compose up -d --remove-orphans --build --pull="always"
    chdir: "{{ containers_setup_configs_dir }}"
  become: true
  changed_when: false
  retries: 2
  tags: [docker, run_docker]
