---

- name: Setup login user, groups and ssh key
  ansible.builtin.include_tasks: user.yml

- name: Setup hostname, network rules and firewall
  ansible.builtin.include_tasks: net.yml

- name: Reboot if required
  when: testing is undefined or testing != 'true'
  block:
    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      ansible.builtin.reboot:
        msg: Rebooting due to a kernel update
      when: reboot_required_file.stat.exists
