---

- name: Ensure the necessary service groups exists
  block:
    - name: Ensure the necessary groups exists
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - docker

- name: Check {{ linux_server_setup_login_user_gid }} already occupied, save name
  ansible.builtin.shell: getent group {{ linux_server_setup_login_user_gid }}
  register: group_with_id_exists
  changed_when: false
  failed_when: false
- name: Check {{ linux_server_setup_login_user_uid }} already occupied, save name
  ansible.builtin.shell: getent passwd {{ linux_server_setup_login_user_uid }}
  register: user_with_id_exists
  changed_when: false
  failed_when: false

- name: If other group with other name and same id exists, delete it
  ansible.builtin.group:
    name: "{{ group_with_id_exists.stdout.split(':')[0] }}"
    state: absent
  when: group_with_id_exists.stdout != "" and group_with_id_exists.stdout.split(':')[0] != linux_server_setup_login_user
- name: If other user with other name and same id exists, delete it
  ansible.builtin.user:
    name: "{{ user_with_id_exists.stdout.split(':')[0] }}"
    state: absent
  when: user_with_id_exists.stdout != "" and user_with_id_exists.stdout.split(':')[0] != linux_server_setup_login_user

- name: Create a login user group
  when: group_with_id_exists
  ansible.builtin.group:
    name: "{{ linux_server_setup_login_user }}"
    gid: "{{ linux_server_setup_login_user_gid }}"
    state: present

- name: Create a login user
  ansible.builtin.user:
    name: "{{ linux_server_setup_login_user }}"
    password: "{{ linux_server_setup_login_password | password_hash('sha512') }}"
    uid: "{{ linux_server_setup_login_user_uid }}"
    groups:
      - sudo
      - docker
      - users
    state: present
    append: true

- name: Chmod the user home directory
  ansible.builtin.file:
    path: "/home/{{ linux_server_setup_login_user }}"
    state: directory
    mode: 0755
    owner: "{{ linux_server_setup_login_user }}"
    group: "{{ linux_server_setup_login_user }}"
    recurse: true

- name: Copy the public SSH key
  ansible.posix.authorized_key:
    user: "{{ linux_server_setup_login_user }}"
    state: present
    key: "{{ linux_server_setup_login_ssh_public_key }}"
  when: testing is undefined or testing != 'true'

- name: Allow sudo group to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Disable cron e-mail notifications
  ansible.builtin.cron:
    name: MAILTO
    user: "{{ linux_server_setup_login_user }}"
    env: true
    job: ""
