name: "Test playbooks"


on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "23 2 * * 2"  # semi-random time once a week

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies

      - name: Install python and ansible requirements
        run: |
          python -m pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Create dummy .vault_pass.txt
        run: |
          echo "test" > .vault_pass.txt

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint

  test-macbook-playbook:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Uninstall GitHub Actions' built-in Homebrew
        run: sudo /bin/bash tests/uninstall-homebrew.sh

      - name: Uninstall GitHub Actions' built-in browser installs
        run: |
          ls -lah /Applications
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app
          sudo rm -rf /usr/local/bin/firefox
          sudo rm -rf /usr/local/bin/chromedriver

      - name: Install python and ansible requirements
        run: |
          python -m pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Create .vault_pass.txt
        run: |
          echo "${{ secrets.VAULT_PASS }}" > .vault_pass.txt

      - name: Test the playbook's syntax
        run: ansible-playbook playbook_macbook.yml -i inventory-test.ini --syntax-check

      - name: Test the playbook
        run: ansible-playbook playbook_macbook.yml -i inventory-test.ini -e "testing=true" -e "admin_password=admin_password user_account_password=" --skip-tags "mas"
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook playbook_macbook.yml -i inventory-test.ini -e "testing=true" -e "admin_password=admin_password user_account_password=" --skip-tags "mas" | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'

  test-vps-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Debug print /etc/resolv.conf  # TODO: remove this debug print
        run: | 
          echo "/etc/resolv.conf"
          cat /etc/resolv.conf
          echo "/etc/systemd/resolved.conf"
          cat /etc/systemd/resolved.conf
          echo "/run/systemd/resolve/resolv.conf"
          cat /run/systemd/resolve/resolv.conf

#      - name: Disable github actions systemd-resolved
#        run: sudo /bin/bash tests/disable-systemd-resolved.sh

#      - name: Setup to free up port 53
#        run: sudo /bin/bash tests/edit-systemd-resolved.sh
#
#      - name: Debug ping google.com  # TODO: remove this debug print
#        run: ping -c 3 google.com

      - name: Install python and ansible requirements
        run: |
          python -m pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Create .vault_pass.txt
        run: |
          echo "${{ secrets.VAULT_PASS }}" > .vault_pass.txt

      - name: Test the playbook's syntax
        run: ansible-playbook playbook_vps.yml -i inventory-test.ini --syntax-check

      - name: Test the playbook
        run: ansible-playbook playbook_vps.yml -i inventory-test.ini -e "testing=true" --skip-tags "run_docker"
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook playbook_vps.yml -i inventory-test.ini -e "testing=true" --skip-tags "run_docker" | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'

#      - name: Enable github actions systemd-resolved
#        run: sudo /bin/bash tests/enable-systemd-resolved.sh

  test-homelab-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Debug print /etc/resolv.conf  # TODO: remove this debug print
        run: | 
          echo "/etc/resolv.conf"
          cat /etc/resolv.conf
          echo "/etc/systemd/resolved.conf"
          cat /etc/systemd/resolved.conf
          echo "/run/systemd/resolve/resolv.conf"
          cat /run/systemd/resolve/resolv.conf

#      - name: Disable github actions systemd-resolved
#        run: sudo /bin/bash tests/disable-systemd-resolved.sh

#      - name: Setup to free up port 53
#        run: sudo /bin/bash tests/edit-systemd-resolved.sh
#
#      - name: Debug ping google.com  # TODO: remove this debug print
#        run: ping -c 3 google.com

      - name: Install python and ansible requirements
        run: |
          python -m pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Create .vault_pass.txt
        run: |
          echo "${{ secrets.VAULT_PASS }}" > .vault_pass.txt

      - name: Test the playbook's syntax
        run: ansible-playbook playbook_homelab.yml -i inventory-test.ini --syntax-check

      - name: Test the playbook
        run: ansible-playbook playbook_homelab.yml -i inventory-test.ini -e "testing=true" --skip-tags "run_docker"
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook playbook_homelab.yml -i inventory-test.ini -e "testing=true" --skip-tags "run_docker" | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'

#      - name: Enable github actions systemd-resolved
#        run: sudo /bin/bash tests/enable-systemd-resolved.sh
